spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/community}
    username: ${DB_USERNAME:community}
    password: ${DB_PASSWORD:community}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    com.example.community: INFO
